### PR TITLE
Add Prometheus Adapter as a dependency

### PR DESCRIPTION
**Pull request by tyler-galileo**
Continuing to drive parity with our Kubernetes manifest deployments, this PR adds Prometheus Adapter as a dependency.

I also added a pre-commit GitHub action to automate checks on PRs and merges.

### CODE REVIEW

**Review by setu4993 — APPROVED** [review]

**Review by ShuaiShao93 — APPROVED** [review]
Nice! Do you mind running `kubectl -n galileo get hpa` to confirm there is no `unknown` for runner hpa?

**Comment by tyler-galileo** [comment]
> Nice! Do you mind running `kubectl -n galileo get hpa` to confirm there is no `unknown` for runner hpa?

➜  helm-charts git:(tyler/prometheus-adapter) ✗ kubectl -n galileo get hpa
No resources found in galileo namespace.

**Comment by ShuaiShao93** [comment]
> > Nice! Do you mind running `kubectl -n galileo get hpa` to confirm there is no `unknown` for runner hpa?
> 
> ```shell
> ➜  helm-charts git:(tyler/prometheus-adapter) ✗ kubectl -n galileo get hpa
> No resources found in galileo namespace.
> ```

What's the namespace? Isn't it galileo?

**Comment by tyler-galileo** [comment]
> What's the namespace? Isn't it galileo?

No HPAs are currently enabled in the Helm charts.

**Comment by ShuaiShao93** [comment]
> > What's the namespace? Isn't it galileo?
> 
> No HPAs are currently enabled in the Helm charts.

So we always have the initial number of API/runner/wizard pods? This is not good, right?

**Comment by tyler-galileo** [comment]
> So we always have the initial number of API/runner/wizard pods? This is not good, right?

These defaults can be configured, or overridden by customers themselves depending on their needs.

**Pull request merged**
